[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 10000
via_ir = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 110
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 64
fail_on_revert = false

[rpc_endpoints]
arc_testnet = "${ARC_RPC_URL}"
